### ISSUE TITLE
Saturn 1.0 : progress tracking

### ISSUE THREAD

**Issue by lyrm** [ocaml-multicore/saturn#123]
The release of Saturn 1.0 coming soon, here is a recap of what has been done and what we plan to do before it !

New features:
- [x] #102 
- [x] #99 
- [x] #83 
- [x] #117 

Better interface and documentation: 
- [x] First round of documentation improvement: #91 
- [x] Standardize data structures API and add simple but user-friendly functions : #92 
- [x] Examples (partially done in #59)
- [x]  Duplicate data structures into safe/unsafe versions when necessary : safe = no unsafe use of `Obj.magic` / unsafe = extensive use of `Obj.magic` with great performances. 
- [x] Second round of documentation improvement

Testing: 
- [x] Dscheck tests for all data structures 
- [x] STM tests for all data structures
- [x] Benchmarks

**Comment by lyrm** [comment]
Most of the goals for the release (and even more) have been achieved. The ETA for the Saturn 1.0 release is now set for the beginning of next week!

**Comment by lyrm** [comment]
Saturn 1.0 has been released 🪐 !
